### chatbox
@url_dev=http://localhost:5000
POST {{url_dev}}/chatbot
Content-Type: application/json

{   
    "stream": true,
    "messages": [ { "role": "user", "content": "Create chatbox using jsx." }]
}